{"name": "test_dodawania[5-8]", "status": "failed", "statusDetails": {"message": "AssertionError: Suma dwóch takich samych składników powinna być równa 10\nassert 8 == (5 + 5)", "trace": "skladnik = 5, suma = 8\n\n    @pytest.mark.parametrize(\"skladnik, suma\", [(5,8),(2,6)])\n    def test_dodawania(skladnik,suma):\n>       assert suma == skladnik + skladnik, \"Suma dwóch takich samych składników powinna być równa \" + str(skladnik+skladnik)\nE       AssertionError: Suma dwóch takich samych składników powinna być równa 10\nE       assert 8 == (5 + 5)\n\nTests\\for_test.py:42: AssertionError"}, "parameters": [{"name": "skladnik", "value": "5"}, {"name": "suma", "value": "8"}], "start": 1636402233619, "stop": 1636402233619, "uuid": "3d9d84e4-7b37-46af-bd72-b7f57e02b0f1", "historyId": "3b391534a5bfaef7be5990d701c52a7d", "testCaseId": "f4546c1ddbd651cbfa15f886ac2bc154", "fullName": "Tests.for_test#test_dodawania", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "for_test"}, {"name": "host", "value": "Karol-Komputer"}, {"name": "thread", "value": "11816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.for_test"}]}